### ISSUE TITLE
13th column in layout's first row 

### ISSUE THREAD

**Issue by covah901** [TeXitoi/keyberon-f4#1]
src/main.rs

In the layout, I noticed the first row has a 13th column. First time submitting an issue, so not sure how to link directly to the file

**Comment by TeXitoi** [comment]
That's a feature. The 13th column is the hardware button on the Dev board. As the button activate all the column, the others should be no action, and not having the value is equivalent to no action.

**Comment by TeXitoi** [comment]
I'll add a comment explaining that later on the source code before closing this issue.

**Comment by covah901** [comment]
Thank you for explaining.
