### ISSUE TITLE
PCB image

### ISSUE THREAD

**Issue by BoKKeR** [TeXitoi/keyberon-f4#2]
Could you provide a better image of the board for my site? https://keyb.io/parts/B08JvZqrS/Keyberon-f4

**Comment by TeXitoi** [comment]
Hi.

Sorry for the delay. What's wrong with https://github.com/TeXitoi/keyberon-f4/raw/master/images/keyberon-44.jpg ?

**Comment by BoKKeR** [comment]
The picture aspect was off and it’s a full keyboard. Not pcb only 😅

**Comment by TeXitoi** [comment]
Mmm, so what can I do to help you?

**Comment by BoKKeR** [comment]
Do you have a picture of the bare pcb by any chance ? No components soldered in

**Comment by TeXitoi** [comment]
That's a handwired keyboard

**Comment by BoKKeR** [comment]
Ah okay! My bad!
