### ISSUE TITLE
Two keystokes registered on single button press

### ISSUE THREAD

**Issue by rurigk** [TeXitoi/keyberon-f4#4]
Hi, i'm using this as the base to build a custom keyboard but i'm having trouble with some weird behaviour

When i press any key of the columns 1, 2 or 3 the key below also get detected

If i bypass the diode the key works as expected

This is my schematic
![image](https://user-images.githubusercontent.com/6665402/167964867-95669bc6-8a1a-46a5-83b7-18ed04b3d514.png)

I already check of shortcircuits, diode orientation

This is my second kb using keyberon but the other is using the bluepill (is using the same grid style)

Any idea why is happening? Thank you

**Comment by dariogoetz** [comment]
When I had a similar issue with a blackpill based board running at 85 MHz, I could solve it by using the latest commit of keyberon (adds support for delays in the matrix scanning) and adding a short delay of 20us in the matrix scanning.

Maybe it's worth a try.
